name: Run tests
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Code quality
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: '**/go.sum'

      - name: Vet and build
        run: |
          go vet ./...
          go build ./...

      - name: Unit tests
        run: go test ./... -v -short
